import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

import TranslationsProvider from '@/components/TranslationsProvider';
import initTranslations from '../i18n';

import i18nConfig from '@/i18nConfig';
import { dir } from 'i18next';

const inter = Inter({ subsets: ['latin'] });

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const i18nNamespaces = ['nav'];

export default async function RootLayout({ children, params: { locale } }) {
  const { resources } = await initTranslations(locale, i18nNamespaces);
  return (
    <html lang={locale} dir={dir(locale)}>
      <body
        className={`${inter.className} flex flex-col h-[100vh] justify-between`}
      >
        <TranslationsProvider
          namespaces={i18nNamespaces}
          locale={locale}
          resources={resources}
        >
          <Navbar />
        </TranslationsProvider>

        {children}
        <Footer />
      </body>
    </html>
  );
}
